create table Person (
                        id int generated by default as identity primary key,
                        name varchar(100) not null,
                        age int,
                        email varchar(100)
);